### ISSUE TITLE
Active Directory app uses the wrong values for dn

### ISSUE THREAD

**Issue by Jeff-Lowrey** [Shuffle/Shuffle-apps#201]
The active-directory app currently hard-codes the LDAP DN value that it passes to ActiveDirectory, as follows:
    `user_dn = "CN=" + samaccountname + "," + base_dn`

"CN=amaccountname" wi

A suggested fix is to replace the call 
```        userAccountControl = json.loads(
            await self.user_attributes(
                server,
                port,
                domain,
                login_user,The active-directory app currently hard-codes the LDAP DN value that it passes to ActiveDirectory, as follows:
    `user_dn = "CN=" + samaccountname + "," + base_dn`

This makes too many assumptions about how the LDAP is structured.

A suggested fix is to replace the call 
```        userAccountControl = json.loads(
            await self.user_attributes(
                server,
                port,
                domain,
                login_user,
                password,
                base_dn,
                use_ssl,
                samaccountname,
                search_base,
            )
        )["attributes"]["userAccountControl"]
```

with

```
           result = json.loads(
            await self.user_attributes(
                server,
                port,
                domain,
                login_user,
                password,
                base_dn,
                use_ssl,
                samaccountname,
                search_base,
            )
        )
```
and then use the "dn" value like `user_dn = results["dn"]`

**Comment by frikky** [comment]
Hey @Jeff-Lowrey! Nice catch - this was made quite a while back, and for a few specific users, hence the specifics. A part of Shuffle has and will always be to make a few assumptions for simplicity sake, as long as it doesn't create other problems as you've shown us here.

After making the changes; would you mind testing it for us in your environment?

Thanks!

**Comment by Jeff-Lowrey** [comment]
We've tested it, actually. And the person who knows more about LDAP than I do says that  "CN=" + samaccountname  will never succeed.

This is what we ended up with for change user password at next login:
```    # Change User Password at Next Logon
    async def change_password_at_next_logon(
        self,
        server,
        port,
        domain,
        login_user,
        password,
        base_dn,
        use_ssl,
        samaccountname,
        search_base,
    ):
        if search_base:
            base_dn = search_base

        c = self.__ldap_connection(server, port, domain, login_user, password, use_ssl)

        result = json.loads(
            await self.user_attributes(
                server,
                port,
                domain,
                login_user,
                password,
                base_dn,
                use_ssl,
                samaccountname,
                search_base,
            )
        )
        userAccountControl = result["attributes"]["userAccountControl"]

        if "DONT_EXPIRE_PASSWORD" in userAccountControl:
            return "Error: Flag DONT_EXPIRE_PASSWORD is set."
        else:
            user_dn = result["dn"]
            password_expire = {"pwdLastSet": (MODIFY_REPLACE, [0])}
            c.modify(dn=user_dn, changes=password_expire)
            c.result["samAccountName"] = samaccountname

            return json.dumps(c.result)

```

**Comment by Jeff-Lowrey** [comment]
But, yes, if you update, we're happy to test your changes.

**Comment by frikky** [comment]
> But, yes, if you update, we're happy to test your changes.

Glad we got some good LDAP people out there :fire:

If you'd like the credits; please make a pull request since you've got it working! Having more contributors help the project makes it more visible to everyone anyway. Happy to do it on our side as well of course!

**Comment by wbnod** [comment]
Test environment: Windows 2012 R2 AD controller using LDAP without SSL (tcp/389). Note that set_password() will never work via the unencrypted protocol, as AD will refuse. That function needs an extra `result = json.loads(await self.user_attributes()...) `call that isn't present to fix the "dn" bug.

Functions enable_user() and disable_user() also have the "dn" bug in addition to the change_password_at_next_logon() above.

**Comment by wbnod** [comment]
The other app, "AD LDAP", has a bug where it does not respect the `use_ssl = false` setting, and so will never work with unencrypted AD LDAP. I can't find my log atm to open a separate issue, but it's there.
