### ISSUE TITLE
Sleep for 10 seconds before proceeding to the next step

### ISSUE THREAD

**Issue by 219liangyi** [Shuffle/Shuffle-apps#211]
I have many such scenarios: after an app is executed to the next node, I need to sleep for 10 seconds before execution. Can it be implemented now?
Look forward to more use explanation documents

**Comment by frikky** [comment]
You can use the "sleep" feature in the "Testing" app. This is not optimal at all, but should solve your usecase.

There are also ways to do this with Bash and Liquid formatting in literally any app.

**Comment by 219liangyi** [comment]
thank
